//Teste de requisições - Categoria

@baseURL = http://localhost:4000

@id = 60b639dd4ede1b7123be3ea0

###
// GET Lista as categorias
GET {{baseURL}}/categorias
Content-Type: application/json

###
// GET Lista a categoria pelo id
GET {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//POST - Inclui uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{"nome": "Alimentos", "status": "ativo"}

###
// DELETE - Apaga uma categoria
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
// PUT - Alterar categoria
PUT {{baseURL}}/categorias
Content-Type: application/json

{
    "_id": "60b6963c7ab9ce0fb287b0b4",
    "nome": "Alimentício",
    "status": "ativo"
}