// Teste de requisições - Produto

@baseURL = http://localhost:4000

@id = 60bd78d176dc880479f8a4c4

###
// GET - Lista os produtos
GET {{baseURL}}/produtos
Content-Type: application/json

###
// GET - Lista um produto pelo id
GET {{baseURL}}/produtos/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo produto
POST {{baseURL}}/produtos
Content-Type: application/json

{
"nome": "Rexona", 
"status": "ativo",
"valor": 10.50,
"quantidade": 5,
"data_abastecimento": "01/06/2021",
"data_vencimento": "05/06/2021"
}

###
// DELETE - Apaga um produto
DELETE {{baseURL}}/produtos/{{id}}
Content-Type: application/json

###
// PUT - Alterar produto
PUT {{baseURL}}/produtos
Content-Type: application/json

{
"_id": "60bd78d176dc880479f8a4c4",
"nome": "Rexona Feminino alterado", 
"status": "ativo",
"valor": 10.80,
"quantidade": 10,
"data_abastecimento": "01/06/2021",
"data_vencimento": "05/06/2021"
}